name: Katalon Test Execution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    env:
      KATALON_VERSION: 9.2.0
      KATALON_PROJECT_PATH: DemoTest.prj
      KATALON_TEST_SUITE: "Test Suites/DemoSuite"
      BROWSER: "Chrome (headless)"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install general dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl jq xvfb libxi6 libnss3

      - name: Install libdbus-glib-1-2 dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-glib-1-2

      - name: Install libgconf-2-4 workaround
        run: |
          sudo add-apt-repository universe -y
          sudo apt-get update

          # Download .deb packages
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gconf/gconf2-common_3.2.6-7ubuntu2_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gconf/libgconf-2-4_3.2.6-7ubuntu2_amd64.deb

          sudo dpkg -i gconf2-common_3.2.6-7ubuntu2_all.deb
          sudo dpkg -i libgconf-2-4_3.2.6-7ubuntu2_amd64.deb

          sudo apt-get install -f -y

      - name: Get Chrome & ChromeDriver download URLs
        id: chrome_urls
        run: |
          JSON_URL="https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
          CHROME_URL=$(curl -sL "$JSON_URL" \
            | jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64") | .url')
          CHROMEDRIVER_URL=$(curl -sL "$JSON_URL" \
            | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          echo "CHROME_DOWNLOAD_URL=$CHROME_URL" >> $GITHUB_ENV
          echo "CHROMEDRIVER_DOWNLOAD_URL=$CHROMEDRIVER_URL" >> $GITHUB_ENV

      - name: Download and install Chrome and ChromeDriver
        run: |
          # Chrome
          curl -sL -o chrome-linux64.zip "$CHROME_DOWNLOAD_URL"
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/google/chrome
          sudo ln -sf /opt/google/chrome/chrome /usr/bin/google-chrome

          # ChromeDriver
          curl -sL -o chromedriver-linux64.zip "$CHROMEDRIVER_DOWNLOAD_URL"
          unzip chromedriver-linux64.zip
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

      - name: Download Katalon Studio Engine (Linux)
        run: |
          wget -q "https://github.com/katalon-studio/katalon-studio/releases/download/v${KATALON_VERSION}/Katalon_Studio_Engine_Linux_64-${KATALON_VERSION}.tar.gz"
          tar -xzf "Katalon_Studio_Engine_Linux_64-${KATALON_VERSION}.tar.gz"

      - name: Debug: List extracted files to find Katalon Engine folder
        run: |
          echo "Listing contents in workspace:"
          ls -lah
          echo "Directories matching pattern:"
          ls -d Katalon_Studio_Engine_Linux_64-* || ls

      - name: Run Katalon Test Suite
        run: |
          KSE_DIR=$(ls -d Katalon_Studio_Engine_Linux_64-* | head -n 1)
          echo "Using engine directory: $KSE_DIR"
          chmod +x "$KSE_DIR/katalon"
          "./$KSE_DIR/katalon" -noSplash \
            -runMode=console \
            -projectPath="${GITHUB_WORKSPACE}/${KATALON_PROJECT_PATH}" \
            -retry=0 \
            -testSuitePath="${KATALON_TEST_SUITE}" \
            -executionProfile=default \
            -browserType="${BROWSER}" \
            --config webui.driver.chrome.path=/usr/local/bin/chromedriver \
            --config webui.autoUpdateDrivers=true

      - name: Archive Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-reports
          path: |
            ${{ github.workspace }}/Reports/**
          retention-days: 14
          include-hidden-files: true
          if-no-files-found: error
