name: Katalon Test Execution

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    env:
      KATALON_VERSION: 9.2.0
      KATALON_PROJECT_PATH: DemoTest.prj
      KATALON_TEST_SUITE: "Test Suites/DemoSuite"
      BROWSER: "Chrome (headless)"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl jq xvfb libxi6 libnss3

      - name: Get latest Chrome version
        id: chrome_version
        run: |
          LATEST_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json | jq -r '.channels.Stable.version')
          echo "CHROME_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Install Chrome and ChromeDriver
        run: |
          # Download Chrome
          curl -sL -o chrome.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chrome-linux64.zip"
          unzip chrome.zip
          sudo mv chrome-linux64 /opt/google/chrome
          sudo ln -sf /opt/google/chrome/chrome /usr/bin/google-chrome

          # Download ChromeDriver
          curl -sL -o chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

      - name: Download Katalon Studio Engine
        run: |
          wget -q https://github.com/katalon-studio/katalon-studio/releases/download/v$KATALON_VERSION/Katalon_Studio_Engine_Linux_64-$KATALON_VERSION.tar.gz
          tar -xzf Katalon_Studio_Engine_Linux_64-$KATALON_VERSION.tar.gz

      - name: Run Katalon Test Suite
        run: |
          ./Katalon_Studio_Engine_Linux_64-$KATALON_VERSION/katalon -noSplash \
            -runMode=console \
            -projectPath=$GITHUB_WORKSPACE/$KATALON_PROJECT_PATH \
            -retry=0 \
            -testSuitePath="$KATALON_TEST_SUITE" \
            -executionProfile=default \
            -browserType="$BROWSER" \
            --config webui.driver.chrome.path=/usr/local/bin/chromedriver \
            --config webui.autoUpdateDrivers=true

      - name: Archive Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-reports
          path: |
            $GITHUB_WORKSPACE/Reports/**
